# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a29865f45c5b9db28f14098f4b95118f"
name = "minder-menu"
handle = "minder-menu"
application_url = "https://july-adolescent-pepper-durham.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "danyn1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://july-adolescent-pepper-durham.trycloudflare.com/auth/callback",
  "https://july-adolescent-pepper-durham.trycloudflare.com/auth/shopify/callback",
  "https://july-adolescent-pepper-durham.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
